name: osFree userland Windows build and tests

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch

    # run at the event pushed by Jenkins
    repository_dispatch:

    push:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: windows-latest

        defaults:
            run:
                shell: cmd

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Check out from repository
              uses: actions/checkout@v3
              with:
                  # repository: {owner}/repo
                  token: ${{ secrets.GITHUB_TOKEN }}
                  submodules: recursive

            # Update references
            - name: Git Sumbodule Update
              run: |
                  git submodule update --init --recursive --force --remote

            # Commit
            #- name: Commit update
            #  run: |
            #      git config --global user.name 'Git bot'
            #      git config --global user.email 'bot@noreply.github.com'
            #      git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            #      git commit -a -m "Auto updated submodule references" || echo "No changes to commit #1"
            #      git push || echo "No changes to commit #2"

            # Install prerequisites
            - name:  Install prerequisites
              run:   tools\conf\scripts\_setup.bat

            # Build
            - name:  Build
              run:   _wcc.cmd
