name: osFree userland Linux build and tests

on:
    # run at the event pushed by Jenkins
    repository_dispatch:

    # run at the event pushed by Jenkins
    push:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:

    # This workflow contains a single job called "build"
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Check out from repository
              uses: actions/checkout@v3
              with:
                  # repository: {owner}/repo
                  token: ${{ secrets.GITHUB_TOKEN }}
                  submodules: recursive

            # Update references
            - name: Git Sumbodule Update
              run: |
                  git submodule update --init --recursive --force --remote

            # Commit
            #- name: Commit update
            #  run: |
            #      git config --global user.name 'Git bot'
            #      git config --global user.email 'bot@noreply.github.com'
            #      git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            #      git commit -a -m "Auto updated submodule references" || echo "No changes to commit #1"
            #      git push || echo "No changes to commit #2"

            # Install prerequisites
            - name:  Install prerequisites
              run:   sudo ./tools/conf/scripts/_setup.sh

            # Build
            - name: Build
              run:   sudo ./_wcc.sh
